### ISSUE TITLE
Cannot change junit xml testsuite attributes

### ISSUE THREAD

**Issue by ankitkadali** [jest-community/jest-junit#87] opened 2019-02-14 20:47 UTC
i have my package.json as below:

```json
"scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test --env=jsdom",
        "test:cov": "yarn test -- --coverage",
        "test:ci": "react-scripts test --env=jsdom --reporters=jest-junit ./node_modules/jest-junit -- 
         coverage ",
        "eject": "react-scripts eject",
        "lint": "eslint src",
        "dev": "node server & react-scripts start",

        "jest-junit": {
          "reporters":["jest-junit"],
           "output": "./junit.xml",
           "classNameTemplate": "{classname}-{title}",
           "titleTemplate": "{classname}-{title}",
           "ancestorSeparator": " › ",
           "suiteNameTemplate": "{filename|filepath|ancestorTitles}",
           "usePathForSuiteName": "true"
       }
    },
```

But junit-xml file still uses the default string present in describe() of test cases. can you help me how can i configure junit-xml file.

**Comment by palmerj3** [comment] 2019-02-14 21:45
@ankitkadali I'm not able to reproduce this. I just created a CRA app locally, added jest-junit, and used the following configuration in my package.json and it works fine. 

Please create a separate repository showing the issue if you believe this is a legitimate problem.

```
{
  "name": "foo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.8.2",
    "react-dom": "^16.8.2",
    "react-scripts": "2.1.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --ci --reporters=default --reporters=jest-junit",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "jest-junit": "^6.2.1"
  },
  "jest-junit": {
     "output": "./junit3.xml",
     "classNameTemplate": "{classname}-{title}",
     "titleTemplate": "{classname}-{title}",
     "ancestorSeparator": " › ",
     "suiteNameTemplate": "{filepath}",
     "usePathForSuiteName": "true"
 }
}
```

**Comment by ankitkadali** [comment] 2019-02-15 14:50
Thank you for your response @palmerj3. I found the way out . instead of 
"test": "**react-scripts test --ci** --reporters=default --reporters=jest-junit",
i was using : react-scripts test --env=jsdom

But right now after the change i made, it is causing one of my test case to fail which passed successfully using without jest-junit. Is there any possible issue with the following test case while using jest-junit?

import React from 'react';
import ReactDOM from 'react-dom';
import { createStore, applyMiddleware } from 'redux'
import { Provider } from 'react-redux'
import { BrowserRouter } from 'react-router-dom'
import thunk from 'redux-thunk'
import fetchMock from 'fetch-mock';
import Viewport from './Viewport';
import reducer from '../reducers'

/*
fetchMock.get('*', {
    "items": [{
        "name": "sample_spec",
        "baseline": "sample_spec",
        "path": "/my_abspath",
        "owner": "pcs",
        "description": "sample network",
        "lastModified": 1524088114653
    }]
});
*/

fetchMock.get('*', (url, opts) => {
    if (url.endsWith('topology.json')) {
        return {
            facilities: [],
            nodes: [],
            links: [],
            topoObjectType: "topology",
            topologyIndex: 1
        };
    } else if (url.endsWith('lsp.json')) {
        // TODO
    }

    return [];
})

function storageMock() {
    return {
        getItem() {
            return null;
        },
        removeItem() {
            // nothing to do
        }
    };
}

window.localStorage = storageMock();

describe('testing ViewPort ', () => {
  it('renders without crashing', () => {
    const store = createStore(
        reducer,
        applyMiddleware(thunk)
    )

    const div = document.createElement('div');
    ReactDOM.render(
        <Provider store={store}>
            <BrowserRouter>
                <Viewport />
            </BrowserRouter>
        </Provider>,
        div);
  //  ReactDOM.unmountComponentAtNode(div);

});
})

The moment i exclude this particular test suite, it runs successfully but if i include this one, i get error Command failed with exit code 1.

The test case error is : window is not defined

**Comment by palmerj3** [comment] 2019-02-15 14:56
It's beyond the scope of jest-junit for this, I believe.

But my thought is that you need to include the --env=jsdom bit as well since it appears you removed it.
I would recommend you post on stackoverflow for debugging your test case.

Going to close this issue - good luck

**Closed by palmerj3** 2019-02-15 14:56 UTC
Labels: Needs more info

**Comment by ankitkadali** [comment] 2019-02-15 15:09
> It's beyond the scope of jest-junit for this, I believe.
> 
> But my thought is that you need to include the --env=jsdom bit as well since it appears you removed it.
> I would recommend you post on stackoverflow for debugging your test case.
> 
> Going to close this issue - good luck

Thanks @palmerj3 . I got the way out !! jest-junit needs --ci for its configuration
