### ISSUE TITLE
console.log not outputing in XML

### ISSUE THREAD

**Issue by MRolandd** [jest-community/jest-junit#89] opened 2019-03-11 15:00 UTC
I created a jest config file that looks like this:

```
{
            \"globals\":{
                \"src_dir\": \"$src_dir\",
                \"src_ref_dir\":\"$src_ref_dir\"
                },
                \"reporters\": [
                \"default\",
                [   \"jest-junit\", {
                    \"suiteName\": \"tests\",
                    \"outputDirectory\": \"$user_dir/log\",
                    \"outputName\": \"log.xml\",
                    \"classNameTemplate\": \"{classname}\",
                    \"titleTemplate\": \"test_{title}\",
                    \"ancestorSeparator\": \" › \",
                    \"suiteNameTemplate\":\"MainTest\",
                    \"usePathForSuiteName\": \"false\" 
                    } ]
                ],
                \"testResultsProcessor\": \"jest-junit\"
            }";
```
(I write it dynamically for each test).

and my jest exec cmd is :` "$(npm bin)/jest --testRegex MainTest.js --findRelatedTests $test_file --config=$conf_file --globals --json --rootDir=$rootDir --notify 2>&1"`

I tried different thing but couldn't get console.log to show an output. Something like PHPUnit has with 
` <system-out>output print</system-out>` in it's XML output.
Any solution?

PS: forgot to mantion. I want the` console.log` to output from the  `file to be tested`, not from the  `test file`

**Comment by palmerj3** [comment] 2019-03-11 15:59
Closing since this is a duplicate of https://github.com/jest-community/jest-junit/issues/45

**Closed by palmerj3** 2019-03-11 15:59 UTC
