### ISSUE TITLE
console support

### ISSUE THREAD

**Issue by mfulton26** [jest-community/jest-junit#45] opened 2018-03-30 19:08 UTC
I'm not sure if this is possible but it would be a huge benefit if the results of any `console.log` statements, etc. were made available inside of `<testcase>` elements using `<system-out>` and `<system-err>`.

**Comment by palmerj3** [comment] 2018-03-31 07:46
If I get time this weekend I can revisit this.

But the last time I looked into it I was worried that it would contain too much irrelevant data. My main worry was if people used the [--useStderr cli flag](https://facebook.github.io/jest/docs/en/cli.html#usestderr).

**Comment by palmerj3** [comment] 2018-04-03 15:16
@mfulton26 I THINK that jest already handles this and by the time this information is sent to a testResultsProcessor that it's already in a non-buffered organized format.

If I get some time this week I can confirm that. But feel free to send a PR if you have time and I'll review!

:)

**Comment by palmerj3** [comment] 2019-03-11 16:07
I'm looking at this now and it appears to be doable however the spec we abide by appears that system-out is associated with a test suite (which for jest would be an individual test file with many test cases). Would that be useful?

I am going to make a PR for the fun of it which adds this and get your feedback.

**Comment by SimenB** [comment] 2019-03-11 16:38
Note that it doesn't buffer when `--silent` is passed. Should be fixed, but worth to note

**Comment by palmerj3** [comment] 2019-03-11 16:55
I've submitted a PR which adds this functionality. Please give me your feedback when you can. I'll leave it open for a few days before merging if there is no feedback.

https://github.com/jest-community/jest-junit/pull/90

**Comment by TonyG623** [comment] 2019-05-02 15:00
@palmerj3 I see the PR was merged. Just added the varaible to my jest config as shown:

```reporters: [
    'default',
    [
      'jest-junit',
      {
        suiteName: 'Unit Tests',
        outputDirectory: '.',
        outputName: 'coverage/test-results.xml',
        classNameTemplate: '{classname}-{title}',
        titleTemplate: '{classname}-{title}',
        ancestorSeparator: ' › ',
        usePathForSuiteName: 'true',
        includeConsoleOutput: 'true',
      },
    ],
  ],```

Not seeing any of my console logs in the my xml report tho :/ 

I think I have that set up correctly based on the readme.

**Comment by simonsen78** [comment] 2019-05-03 07:49
I also tried it, same as @TonyG623, and saw no output in my XML report.

**Comment by palmerj3** [comment] 2019-05-03 09:43
Hmm thanks for reporting. Can you both tell me the version(s) of jest you're running this against?

**Comment by simonsen78** [comment] 2019-05-06 06:58
Not sure if this is related, but could it be a Windows vs. Linux path thing somewhere in your code?

Tried cloning the repo and running the tests. Got a bunch of these errors:
```

 ● buildJsonResults › should return the proper name from testFilePath when usePathForSuiteName is "true"; no appDirectory set

   expect(received).toBe(expected) // Object.is equality

   Expected: "path/to/test/__tests__/foo.test.js"
   Received: "path\\to\\test\\__tests__\\foo.test.js"

     101 |         usePathForSuiteName: "true"
     102 |       }));
   > 103 |     expect(jsonResults.testsuites[1].testsuite[0]._attr.name).toBe('path/to/test/__tests__/foo.test.js');
         |                                                               ^
     104 |   });
     105 |
     106 |   it('should return the proper name from testFilePath when usePathForSuiteName is "true"; with appDirectory set', () => {

     at Object.toBe (__tests__/buildJsonResults.test.js:103:63)
```

**Comment by jkblume** [comment] 2019-05-21 16:52
Hi there, join the discussion again and hope i can help a little bit more this time.
Actually we want to test a react project but for testing purpose i created a minimal project setup here:
https://github.com/jkblume/simple-app

Steps to reproduce the error:
- Clone the project and step into it
- ```npm install```
- ```npm run test```
- Check junit.xml does not contain the expected stdout that is logged in test and implementation code

I added some debug output to the jest junit project and found, that the console attribute of the suite object is <code>undefined</code>. Maybe this is already the error?

```javascript
{
    console: undefined,
    ... 
}
```

Hope that a concrete example helps to solve the problem or approach the origin of the error.

**Comment by jkblume** [comment] 2019-05-28 19:15
I dived a little bit into jest core code and found that ReportDispatcher overrides .console property with undefined. I opened an issue to discuss this: https://github.com/facebook/jest/issues/8499

**Comment by brownbl1** [comment] 2019-07-23 17:37
Is there an update on this? I'm seeing the same behavior? Did any of you find a workaround?

**Comment by palmerj3** [comment] 2019-07-23 20:30
Hey sorry for the radio silence on this one. It's somewhat complex.

I believe I have a fix for jest to re-enable this functionality. Will link the PR here shortly and hopefully it's approved.

**Closed** 2019-07-23 21:52 UTC
Labels: enhancement, help wanted

**Comment by palmerj3** [comment] 2019-07-23 21:56
I just published jest-junit 7.0.0 with a fix that should now allow for console output to be written to junit.xml.

A few caveats (due to breaking changes in jest):

1. You must have at least 2 test files in order for console output to be sent to jest-junit
2. You cannot set verbose to true in jests config

**Comment by SimenB** [comment] 2019-07-23 23:45
Both of those caveats are bugs in jest... (https://github.com/facebook/jest/issues/6441 sorta relates, but reporters should always get console output regardless of silent/verbose - it should decide itself based on those options whether to print it or not)

**Comment by CMCDragonkai** [comment] 2022-06-29 02:19
@palmerj3 are those 2 caveats still true?

**Comment by CMCDragonkai** [comment] 2022-06-29 02:27
What's the reason to do this:

> You cannot set verbose to true in jests config
